# Generated by Django 4.0.5 on 2022-06-14 13:44

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_payrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrecord',
            name='payment_date_time',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
