# Generated by Django 4.0.5 on 2022-06-14 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_payrecord_payment_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrecord',
            name='requested_user',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.PositiveBigIntegerField()),
                ('payed', models.BooleanField(default=False)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_in', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payrecord',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Request_set', to='accounting.request'),
        ),
    ]
