# Generated by Django 4.0.5 on 2022-06-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_payrecord_requested_user_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrecord',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Request_set', to='accounting.request'),
        ),
    ]
