# Generated by Django 4.0.5 on 2022-06-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_payrecord_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrecord',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Request_set', to='accounting.request'),
        ),
    ]
